server:
  #服务端端口
  port: 8087
yeyu:

  #Mirai的HTTPAPI的主机地址，本地为127.0.0.1
  host: 127.0.0.1
  #HTTPAPI的端口
  port: 8082
  #HTTPAPI的设置的token
  token: INITKEYbcupcF2N
  #机器人QQ
  robotQQ: 2452589763

  #触发前缀
  startPrefix: 。

  #使用的模式 0为官方API (1为chatGPT 不推荐)
  model: 0

  #API-KEY 使用官方模式时使用 请到官网beta.openai.com/account/api-keys获取key
  apikey: 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

  #session-token 浏览器application中cookie获取__Secure-next-auth.session-token的值 不推荐
  sessionToken: eyJhb....

  #userAent
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

  #cloudfare cookie 浏览器application中cookie获取cf_clearance的值
  cf: nxhH2zLTn1oDqTInOGj3wmGGFlbhiZOcl.CEXlOyK1k-1670916726-0-1-97d62ec.aa68b07b.5e7c3d0c-160



spring:
  main:
    allow-bean-definition-overriding: true